// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPollIntervalMinutes():Promise<number>;

export function ListProviders():Promise<Array<main.ProviderInfo>>;

export function SaveProviderConfig(arg1:string,arg2:boolean,arg3:Record<string, string>):Promise<void>;

export function SetPollIntervalMinutes(arg1:number):Promise<void>;

export function TestConnection(arg1:string,arg2:Record<string, string>):Promise<void>;
