// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutostartEnabled() {
  return window['go']['main']['App']['GetAutostartEnabled']();
}

export function GetPollIntervalMinutes() {
  return window['go']['main']['App']['GetPollIntervalMinutes']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RefreshNow() {
  return window['go']['main']['App']['RefreshNow']();
}

export function SaveProviderConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProviderConfig'](arg1, arg2, arg3);
}

export function SetAutostartEnabled(arg1) {
  return window['go']['main']['App']['SetAutostartEnabled'](arg1);
}

export function SetPollIntervalMinutes(arg1) {
  return window['go']['main']['App']['SetPollIntervalMinutes'](arg1);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}
