// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {main} from '../models';
import {providers} from '../models';
import {store} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdateNow():Promise<updater.Info>;

export function CreateIntegration(arg1:string,arg2:string,arg3:Record<string, string>):Promise<main.IntegrationInfo>;

export function CreateTask(arg1:main.CreateTaskInput):Promise<providers.TaskItem>;

export function DeleteIntegration(arg1:string):Promise<void>;

export function DeletePanel(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetAutostartEnabled():Promise<boolean>;

export function GetComments(arg1:providers.TaskItem):Promise<Array<providers.Comment>>;

export function GetPanelAssignedTasks(arg1:store.Panel):Promise<Array<providers.TaskItem>>;

export function GetPanelCreatedByMeTasks(arg1:store.Panel):Promise<Array<providers.TaskItem>>;

export function GetPollIntervalMinutes():Promise<number>;

export function GetTasks():Promise<Array<providers.TaskItem>>;

export function GetUpdateStatus():Promise<updater.Info>;

export function ListAssignableUsers(arg1:string,arg2:string):Promise<Array<providers.UserOption>>;

export function ListIntegrations():Promise<Array<main.IntegrationInfo>>;

export function ListPanels():Promise<Array<store.Panel>>;

export function ListProjects(arg1:string):Promise<Array<providers.ProjectOption>>;

export function ListProviderTypes():Promise<Array<main.ProviderTypeInfo>>;

export function OpenURL(arg1:string):Promise<void>;

export function RefreshNow():Promise<void>;

export function RefreshTaskItem(arg1:providers.TaskItem):Promise<providers.TaskItem>;

export function SavePanel(arg1:store.Panel):Promise<store.Panel>;

export function SearchTasks(arg1:string):Promise<Array<providers.TaskItem>>;

export function SetAutostartEnabled(arg1:boolean):Promise<void>;

export function SetPollIntervalMinutes(arg1:number):Promise<void>;

export function TestConnection(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function UpdateIntegration(arg1:string,arg2:string,arg3:boolean,arg4:Record<string, string>):Promise<void>;
