// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckForUpdateNow() {
  return window['go']['main']['App']['CheckForUpdateNow']();
}

export function CreateIntegration(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateIntegration'](arg1, arg2, arg3);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteIntegration(arg1) {
  return window['go']['main']['App']['DeleteIntegration'](arg1);
}

export function DeletePanel(arg1) {
  return window['go']['main']['App']['DeletePanel'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutostartEnabled() {
  return window['go']['main']['App']['GetAutostartEnabled']();
}

export function GetComments(arg1) {
  return window['go']['main']['App']['GetComments'](arg1);
}

export function GetPollIntervalMinutes() {
  return window['go']['main']['App']['GetPollIntervalMinutes']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function ListIntegrations() {
  return window['go']['main']['App']['ListIntegrations']();
}

export function ListPanels() {
  return window['go']['main']['App']['ListPanels']();
}

export function ListProjects(arg1) {
  return window['go']['main']['App']['ListProjects'](arg1);
}

export function ListProviderTypes() {
  return window['go']['main']['App']['ListProviderTypes']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RefreshNow() {
  return window['go']['main']['App']['RefreshNow']();
}

export function RefreshTaskItem(arg1) {
  return window['go']['main']['App']['RefreshTaskItem'](arg1);
}

export function SavePanel(arg1) {
  return window['go']['main']['App']['SavePanel'](arg1);
}

export function SearchTasks(arg1) {
  return window['go']['main']['App']['SearchTasks'](arg1);
}

export function SetAutostartEnabled(arg1) {
  return window['go']['main']['App']['SetAutostartEnabled'](arg1);
}

export function SetPollIntervalMinutes(arg1) {
  return window['go']['main']['App']['SetPollIntervalMinutes'](arg1);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}

export function UpdateIntegration(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateIntegration'](arg1, arg2, arg3, arg4);
}
