// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {providers} from '../models';
import {updater} from '../models';

export function ApplyUpdate():Promise<void>;

export function CreateTask(arg1:main.CreateTaskInput):Promise<providers.TaskItem>;

export function GetAppVersion():Promise<string>;

export function GetAutostartEnabled():Promise<boolean>;

export function GetPollIntervalMinutes():Promise<number>;

export function GetTasks():Promise<Array<providers.TaskItem>>;

export function GetUpdateStatus():Promise<updater.Info>;

export function ListProviders():Promise<Array<main.ProviderInfo>>;

export function OpenURL(arg1:string):Promise<void>;

export function RefreshNow():Promise<void>;

export function SaveProviderConfig(arg1:string,arg2:boolean,arg3:Record<string, string>):Promise<void>;

export function SetAutostartEnabled(arg1:boolean):Promise<void>;

export function SetPollIntervalMinutes(arg1:number):Promise<void>;

export function TestConnection(arg1:string,arg2:Record<string, string>):Promise<void>;
